[versions]
agp = "8.13.1"
xposed-api = "82"
androidx-annotation = "1.9.1"
androidx-appcompat = "1.7.1"
androidx-activity = "1.12.0"
androidx-constraintlayout = "2.2.1"
androidx-preference = "1.2.1"
androidx-navigationfragment = "2.9.6"
androidx-navigationui = "2.9.6"
google-material = "1.13.0"
junit = "4.13.2"
junit-version = "1.3.0"
espresso-core = "3.7.0"

[libraries]
xposed-api = { module = "de.robv.android.xposed:api", version.ref = "xposed-api" }
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "androidx-annotation" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "androidx-activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "androidx-constraintlayout" }
androidx-preference = { group = "androidx.preference", name = "preference", version.ref = "androidx-preference" }
androidx-navigationfragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "androidx-navigationfragment" }
androidx-navigationui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "androidx-navigationui" }
google-material = { group = "com.google.android.material", name = "material", version.ref = "google-material" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junit-version" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }

